version: '3.1'

services:
  fast-data:
    image: landoop/fast-data-dev:cp4.0
    ports:
      - "9092:9092"   # Kafka broker
      - "8081:8081"   # Schema Registry
      - "8082:8082"   # Kafka REST Proxy
      - "8083:8083"   # Kafka Connect
      - "2182:2181"   # Zookeeper
      - "3030:3030"   # Landoop Development Environment UI
    environment:
      - "ADV_HOST=127.0.0.1"  # Allow services in container to be remotely accessible (so the host can access it)
      - "SAMPLEDATA=0"        # Do not create example topics
      - "FORWARDLOGS=0"       # Disable the 5 file source connectors that automatically bring logs into Kafka topics
      - "RUNTESTS=0"          # Don't run Coyote integration tests on container startup (enable if debugging)
  cassandra:
      image: cassandra:3.11.1
      ports:
        - "9042:9042"   # Native transport
        - "7199:7199"   # JMX
        - "9160:9160"   # Thrift clients
